### ISSUE TITLE
Getting an error when I try to run the app: Error: Cannot find module './StoryRead'

### ISSUE THREAD

**Issue by alarner** [alarner/pointer-app#11]
While trying to deploy pointer app tonight I got the following error. I believe this is due to the fact that the backend student model created in PR #5 is trying to require a file that does not exist:

@tinydinosaurs can you investigate?

```
Error: Cannot find module './StoryRead'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at require (internal/module.js:16:19)
    at Module.require (module.js:367:17)
    at Object.<anonymous> (/app/models/Student.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /app/node_modules/bookshelf-api/dist/index.js:39:11
    at Array.map (native)
    at module.exports (/app/node_modules/bookshelf-api/dist/index.js:37:21)
    at Object.<anonymous> (/app/routes/api1.js:4:44)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/app/app.js:54:11)
```

**Comment by afmonty** [comment]
The StoryRead module has been created and merged.  This issue should be closed
